plugins { id 'com.android.application' }

android {
    namespace 'com.celltac.gppm'
    compileSdk 35

    defaultConfig {
        applicationId 'com.celltac.gppm'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.0.3'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
